name = "domain-check"
main = "src/index.js"
compatibility_date = "2025-12-25"
keep_vars = true

[[kv_namespaces]]
binding = "DOMAIN_KV" 
id = "42a41cf8d8204935b5f49743484209e5" # action部署时被变量替换

[triggers]
crons = ["0 1,13 * * *"] # 北京时间 9:00 和 21:00
